### ISSUE TITLE
Compatibility with Tidy5e vehicules sheet

### ISSUE THREAD

**Issue by DarKDinDoN** [cstby/foundryvtt-world-currency-5e#1]
Hello,

Thx for this module. Quite handy!
Can you make this compatible with the Tidy5e Vehicule sheet?

![image](https://user-images.githubusercontent.com/1687854/146760379-965b69a7-d4a0-4711-9040-506ff62ba3cb.png)

**Comment by cstby** [comment]
Thanks! It should be possible. I'll look into it.

**Comment by cstby** [comment]
Added support for Tidy5e Vehicle Sheet in https://github.com/cstby/foundryvtt-world-currency-5e/commit/06e2d2bba031105a6eeecd82a449d80c819c3f9d. Thanks again for opening this issue!
