### ISSUE TITLE
Slowdown from new DnD5e v1.6 update?

### ISSUE THREAD

**Issue by GambetTV** [cstby/foundryvtt-world-currency-5e#12]
I'm not sure if this has always been the case or is only just recently happened, but ever since I updated to the latest version of the DnD5e ruleset, updating literally anything on a token causes some level of slowdown. I opened the console and while there are no errors, I'm noticing a ton of 

world-currency-5e | Altered character sheet
Caught actor sheet render hook!

going on. Simply closing an item causes 2 to fire off. Deleting a Class Feature, which doesn't even have a currency field attached to it, causes the above to fire off 15 times, no exaggeration.

This might be working how it always has, I'm not sure, all I can say for sure is after a period of time of messing around in character sheets it seems like Foundry is slowing down. Refreshing fixes it, but so does disabling your module.

I can't say with 100% certainty it's your module causing the issue, but it might be worth taking a look!

**Comment by cstby** [comment]
I'm sorry about the late reply. I haven't had time to reproduce this problem yet. Did it persist? Did disabling the module fix it?

**Comment by cstby** [comment]
I was not able to reproduce this issue. I've made substantial changes to this module for version 2.0, so if you're still encountering these problems on the newest version, please feel free to open a new issue.
