### ISSUE TITLE
Version 10 Planned?

### ISSUE THREAD

**Issue by UmbraZeal** [cstby/foundryvtt-world-currency-5e#14]
Is there a version in the works for version 10 of Foundry VTT?

**Comment by cstby** [comment]
Yes, I do plan to update this module to be fully compatible with version 10. I haven't yet fully tested it yet, so if there's functionality you know to be broken, please let me know.

**Comment by UmbraZeal** [comment]
After some testing it just seems to be needing updating the mod over to version 10 to get rid of the out-of-date warning sign, all features seem to be working fine.
