### ISSUE TITLE
Vehicle page not hiding currency.

### ISSUE THREAD

**Issue by UmbraZeal** [cstby/foundryvtt-world-currency-5e#15]
Vehicle character sheet showing currencies set as hidden while using Tidy5e (happens when using default sheet as well).
(One of the C currencies should be the only one visible like on player character sheet).

![09b26bfe34dc27a97ff1cf37dfef68ce](https://user-images.githubusercontent.com/112840716/192994656-3b8cb90c-4203-4743-9822-4d009513fc66.png)

**Comment by cstby** [comment]
Fixed in https://github.com/cstby/foundryvtt-world-currency-5e/commit/84a89bef4ce51b3521d7506d335922e9a83f1cb8!
