### ISSUE TITLE
 The module is not compatible with foundry v10.

### ISSUE THREAD

**Issue by CepheiA2** [cstby/foundryvtt-world-currency-5e#16]
Hi, i really like this module, but at the moment is not compatible with foundry v10.

**Comment by UmbraZeal** [comment]
It does come up with a version error, but all the features seem to still work.

**Comment by seanma333** [comment]
They don't all work for me. Prices aren't being updated in the item sheets and the hiding feature only hides the currency symbols and not the input boxes on character inventory. I'm pretty sure this is due to v10 using `system` instead of `data`.

**Comment by cstby** [comment]
Last I checked, I was getting her same errors.

I plan to fully update this module to be compatible with v10. 

Right now I'm working the the DND5E system team on my merge request to change how currency conversion is represented. My proposed change will allow for more flexibility in defining custom currencies and hopefully more cross-compatibility between modules that

**Comment by cstby** [comment]
I ended up deciding to refactor before the changes to the DND5E system are merged. This module should now be compatible with v10. This update includes a breaking change that'll require you to set your currency conversion rates again in the module settings. If you run into any v10 compatibility problems, please feel free to open a new issue.
