### ISSUE TITLE
WC5e + Tidy5e NPC Sheet.

### ISSUE THREAD

**Issue by UmbraZeal** [cstby/foundryvtt-world-currency-5e#17]
Running on the newest version of WC5e, hidden currencies are showing on Tidy5e NPC sheets.

![c2987a9745d5a21e83123e3006db0b5e](https://user-images.githubusercontent.com/112840716/198671019-a7673e44-5f6e-42e6-8379-e5244120e7b4.png)

**Comment by cstby** [comment]
Thanks for the report.. that should definitely not be happening. I'm unable to reproduce this issue on my end. I'm on Foundry V10 Build 288, Tidy5e Sheet 0.6.6, and DND5E 2.0.3. What versions are you running?

**Comment by cstby** [comment]
@UmbraZeal Thanks so much for reporting this problem. I've fixed it and cut a new release.
