### ISSUE TITLE
BUG: Anytime I open an item and close it it gives me an error message 

### ISSUE THREAD

**Issue by GambetTV** [cstby/foundryvtt-world-currency-5e#2]
Whenever I open an item from a compendium and close it, even if I don't do anything to it, I get the following error message that pops up over my screen: "You may not modify the dnd5e.items Compendium which is currently locked"

I am using Foundry v9, which might be the problem, but I thought I'd just mention it in case.

**Comment by cstby** [comment]
Thanks for trying this out on v9. I have an idea of what's causing this bug. Have you run into any other issues after upgrading to v9?

**Comment by GambetTV** [comment]
No, but I haven't run a session since upgrading to v9, and this is the first time installing your module, so I haven't really put it through its paces yet. After the holiday season I'll run more games and if I see anything else I'll make sure to report it!

**Comment by DarKDinDoN** [comment]
Hello, still on 0.8.9 here, no bug on compendium.
Seems to be V9 only

**Comment by cstby** [comment]
Thanks for the bug report! I've fixed the issue in 94a5ccd2fb3e9c48873656232bfacbce2fa891c7 and cut a new release.

**Comment by DarKDinDoN** [comment]
@cstby Hey, would you mind marking this module as v9 compatible by the way? `"compatibleCoreVersion": "9"`

**Comment by cstby** [comment]
Sure thing. I haven't had a chance to test all functionality on v9 yet, but this is next on my list. :)
