### ISSUE TITLE
Currency images in the DnD 3.0 character sheet

### ISSUE THREAD

**Issue by diarioz** [cstby/foundryvtt-world-currency-5e#24]
Hey, I really love your module and mostly use it to display the Silver Standard on my players' character sheets.

With the new character sheets from the DnD 3.0 update, currency icons are displayed next to the coin amounts, instead of just text.

There is 2 issues arising with this now and I was wondering if you were planning to expend your module to accomodate for them:

- These new icons can not currently be changed, so my "silver coins" appear with the gold icon next to them
- The icons of the "hidden" currencies still display, see screenshot below:

![image](https://github.com/cstby/foundryvtt-world-currency-5e/assets/161132772/c8d3dc8b-005c-4815-a291-1ecbba6376f2)

**Comment by cstby** [comment]
Thanks for the issue and your kind words. I'm glad to hear that folks still use this module!

I understand the issue and your desired outcome. I'll take a look into the code and see what I can do in the coming weeks. Hiding the icons completely should be possible. The more ideal outcome would be to keep the icons we still want, but that might require changes in the upstream dnd5e repository. I'll need to investigate before I can say more.

**Comment by cstby** [comment]
I submitted a pull request upstream: https://github.com/foundryvtt/dnd5e/pull/3145. My approach to fix the problem will depend on how the dnd5e system maintainers receive the request.

**Comment by kmuld** [comment]
I've submitted a pull request to fix this, as well as removing the 3.0 currency converter.
https://github.com/cstby/foundryvtt-world-currency-5e/pull/25

**Comment by cstby** [comment]
@diarioz Once you update to v2.0.3, you should be all set. I'm closing this issue as completed, but please feel free to reopen if you're still encountering any problems.

**Comment by diarioz** [comment]
Hey, the issue was nicely resolved in 2.0.3 and worked like a charm :)

But after the 2.0.4 update, the feature: "Icons are now based on the currency abbreviation that you choose." 
seems to no longer work. The hiding still works though.
