### ISSUE TITLE
Is there any chance this will come to PF2E in the near future?

### ISSUE THREAD

**Issue by PupperooX** [cstby/foundryvtt-world-currency-5e#3]

**Comment by cstby** [comment]
I consider systems other than D&D 5E to be out of scope.

I would suggest forking this module for PF2E. I'm not very familiar with the PF2E game system for Foundry, nor the ecosystem of modules surrounding it. For that reason, I would not make a very good maintainer of a PF2E currency module. Moreover, the code and implementation assumes D&D 5E in many places. Refactoring it to support more than one game system would introduce a great deal of complexity.

If you could find a developer willing to maintain a PF2E port of this module, I would gladly give them advice on how to convert it.

**Comment by cstby** [comment]
I'm going to close this issue, but if you find a developer willing to work on a port, please do let me know.
