### ISSUE TITLE
Standard Currency prevents changing item prices

### ISSUE THREAD

**Issue by Buzzworth** [cstby/foundryvtt-world-currency-5e#4]
Currently if you change the standard currency to another coin such as silver it will automatically convert the value of all items to that currency. 

So if an item was previously priced at 15, and the conversion rate of gold to silver is 1 to 100 it will now be priced as 1500. 

If you then try to adjust the price to be 15 again it will instantly recalculate it to 1500. 

There needs to be a way to turn off this instant price adjustment so that prices can be adjusted manually as well.

My use case involves wanting to use the silver standard but keep platinum in the mix. This cannot be accomplished currently as you would need to keep the standard on gold and just rename the coins, but may only have one denomination above silver when renamed.

**Comment by cstby** [comment]
Unfortunately, it's not possible to have more than one denomination above the "gp" currency (which would be silver, in your example above). I can explain the reason in more detail of you want, but it's a limitation of the 5e system. It's not possible to fix it from this module at this time.

One workaround would be to create a platinum coin item and treat it more like a gem or a metal trade bar.

**Comment by cstby** [comment]
Fixed the item price update issue in release 1.4.0.
