### ISSUE TITLE
Item Values update far too often

### ISSUE THREAD

**Issue by Almaity** [cstby/foundryvtt-world-currency-5e#6]
I've changed my standard currency to Copper, which adds 00 to the end of each item price / multiplies by 100. Which is great, that is what I wanted.

However, it repeats this process almost anytime I change anything on the item, not just the price, which quickly ends up with prices in the millions for all items. I'm not sure if it's possible to narrow the trigger for the price conversion to just the price field being edited, but perhaps an alternative would be to only allow the conversion on an item card to happen once? (Flag the item somehow that it was already converted, then check that flag before conversion? Flag would also have to be inherited by the item being moved to actors ideally)

Or perhaps instead of automatic conversion, have a one time event edit the prices of everything in the game and compendiums to the new values (And perhaps save a backup somewhere to revert to). Button for that in the settings perhaps?

**Comment by cstby** [comment]
Thanks for the bug report. There is logic in place to revert the price of the item when the item sheet is closed. It must not be working properly.

I'll see if I can replicate the issue. What version of Foundry are you on? Also, do you get any error message in the console when you close the item sheet?
