### ISSUE TITLE
Silver to Gold exchange rate is not present

### ISSUE THREAD

**Issue by TheTeal** [cstby/foundryvtt-world-currency-5e#9]
Looking at the screenshots, there should be a silver to gold exchange rate - it is not present in the settings however and there appears to be no way to set what the exchange rate is for silver to gold.

Screenshot from your readme:
![image](https://user-images.githubusercontent.com/29224974/161202744-ec9bb499-40f7-4b1c-b100-baca278dc247.png)

Actual settings:
![image](https://user-images.githubusercontent.com/29224974/161202662-ac93aabc-3c69-483b-a681-7165f29c3882.png)

**Comment by cstby** [comment]
Version 2.0 makes this a non-issue. All currency rates are now in terms of RAW GP.
